services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: issues-gw:prod
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT:-8080}:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 3s
      retries: 5
